spring: 
  profiles:
    active:
    - dev
--- 
server:
  port: 9001
spring: 
   profiles: dev
   application: 
    name: vpro
   zipkin:
    base-url: http://localhost:9400
    enabled: true
   datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://localhost:3306/valproCloud1
    username: root
    password: 123456
    dbcp2:
      min-idle: 5
      initial-size: 5
      max-total: 5
      max-wait-millis: 200 
mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml
  # type-aliases-package: cn.cindata.valproCloud.entity
  mapper-locations:
  - classpath:mybatis/mapper/**/*.xml
 
eureka: 
  client: #客户端注册进eureka服务列表内
    service-url: 
      defaultZone: http://localhost:9101/eureka
  instance:
    instance-id: userprovider
    prefer-ip-address: true
 
info:
  app.name: valproCloud
  company.name: www.cindata.cn
  build.artifactId: $project.artifactId$
  build.version: $project.version$
---
server:
  port: 9001
spring: 
   profiles: test
   application: 
    name: valproCloud-user-provider
   zipkin:
    base-url: http://localhost:9400
    enabled: true
   datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://localhost:3306/valproCloud2
    username: root
    password: 123456
    dbcp2:
      min-idle: 5
      initial-size: 5
      max-total: 5
      max-wait-millis: 200  
  
  
mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml
  type-aliases-package: cn.cindata.valproCloud.entity
  mapper-locations:
  - classpath:mybatis/mapper/**/*.xml
 
eureka: 
  client: #客户端注册进eureka服务列表内
    service-url: 
      defaultZone: http://localhost:9101/eureka
  instance:
    instance-id: userprovider
    prefer-ip-address: true
 
info:
  app.name: valproCloud
  company.name: www.cindata.cn
  build.artifactId: $project.artifactId$
  build.version: $project.version$

