spring:
  profiles:
    active:
    - dev
---
server: 
  port: 9998
spring:
  profiles: dev
  application: 
    name: valproCloud-config-client
eureka: 
  client: 
    service-url: 
      defaultZone: http://eureka-dev.com:9101/eureka/   
---
server: 
  port: 9997 
spring:
  profiles: test
  application: 
    name: microservicecloud-config-client
eureka: 
  client: 
    service-url: 
      defaultZone: http://eureka-test.com:9101/eureka/
 

