spring: 
  profiles: 
    active: 
    - dev
---
server: 
  port: 9101 #注册中心占用7001端口,冒号后面必须要有空格
   
spring: 
  profiles: dev
  application:
    name: valproCloud-eureka
    
eureka: 
  instance: 
    hostname: eureka9101.com #冒号后面必须要有空格
  client: 
    register-with-eureka: false #当前的eureka-server自己不注册进服务列表中
    fetch-registry: false #不通过eureka获取注册信息
    service-url: 
      defaultZone: http://eureka9101.com:9101/eureka/
---
server: 
  port: 9101 #注册中心占用7001端口,冒号后面必须要有空格
   
spring: 
  profiles: test
  application:
    name: valproCloud-eureka
    
eureka: 
  instance: 
    hostname: eureka9101.com #冒号后面必须要有空格
  client: 
    register-with-eureka: false #当前的eureka-server自己不注册进服务列表中
    fetch-registry: false #不通过eureka获取注册信息
    service-url: 
      defaultZone: http://eureka9101.com:9101/eureka/

